-- AlterTable
ALTER TABLE `ArmadaLog` MODIFY `entityType` ENUM('USER', 'ROLE', 'PERMISSION', 'WAREHOUSE', 'PRODUCT', 'CUSTOMER', 'ARMADA', 'DRIVER', 'DELIVERY_ORDER', 'SHIPMENT', 'SPMB') NOT NULL;

-- AlterTable
ALTER TABLE `CustomerLog` MODIFY `entityType` ENUM('USER', 'ROLE', 'PERMISSION', 'WAREHOUSE', 'PRODUCT', 'CUSTOMER', 'ARMADA', 'DRIVER', 'DELIVERY_ORDER', 'SHIPMENT', 'SPMB') NOT NULL;

-- AlterTable
ALTER TABLE `DeliveryOrderLog` MODIFY `entityType` ENUM('USER', 'ROLE', 'PERMISSION', 'WAREHOUSE', 'PRODUCT', 'CUSTOMER', 'ARMADA', 'DRIVER', 'DELIVERY_ORDER', 'SHIPMENT', 'SPMB') NOT NULL;

-- AlterTable
ALTER TABLE `ProductLog` MODIFY `entityType` ENUM('USER', 'ROLE', 'PERMISSION', 'WAREHOUSE', 'PRODUCT', 'CUSTOMER', 'ARMADA', 'DRIVER', 'DELIVERY_ORDER', 'SHIPMENT', 'SPMB') NOT NULL;

-- AlterTable
ALTER TABLE `SPMB` ADD COLUMN `generatedById` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Shipment` ADD COLUMN `driverId` VARCHAR(191) NULL,
    ADD COLUMN `tally` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `ShipmentLog` MODIFY `entityType` ENUM('USER', 'ROLE', 'PERMISSION', 'WAREHOUSE', 'PRODUCT', 'CUSTOMER', 'ARMADA', 'DRIVER', 'DELIVERY_ORDER', 'SHIPMENT', 'SPMB') NOT NULL;

-- AlterTable
ALTER TABLE `UserLog` MODIFY `entityType` ENUM('USER', 'ROLE', 'PERMISSION', 'WAREHOUSE', 'PRODUCT', 'CUSTOMER', 'ARMADA', 'DRIVER', 'DELIVERY_ORDER', 'SHIPMENT', 'SPMB') NOT NULL;

-- AlterTable
ALTER TABLE `WarehouseLog` MODIFY `entityType` ENUM('USER', 'ROLE', 'PERMISSION', 'WAREHOUSE', 'PRODUCT', 'CUSTOMER', 'ARMADA', 'DRIVER', 'DELIVERY_ORDER', 'SHIPMENT', 'SPMB') NOT NULL;

-- CreateTable
CREATE TABLE `Driver` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateIndex
CREATE INDEX `SPMB_generatedById_fkey` ON `SPMB`(`generatedById`);

-- CreateIndex
CREATE INDEX `Shipment_driverId_fkey` ON `Shipment`(`driverId`);

-- AddForeignKey
ALTER TABLE `Shipment` ADD CONSTRAINT `Shipment_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `Driver`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SPMB` ADD CONSTRAINT `SPMB_generatedById_fkey` FOREIGN KEY (`generatedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
