-- AlterTable
ALTER TABLE `DeliveryOrder` MODIFY `status` ENUM('PENDING', 'PROSES', 'SELESAI', 'CANCEL') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `Shipment` MODIFY `status` ENUM('PENDING', 'PROSES', 'SELESAI', 'CANCEL') NOT NULL DEFAULT 'PENDING';
