-- AlterTable
ALTER TABLE `Permission` MODIFY `action` ENUM('CREATE', 'READ', 'UPDATE', 'DELETE', 'WEIGH', 'VERIFY_PLATE', 'VERIFY_PLATE_MANUAL', 'CHANGE_CUSTOMER', 'REVISE_DO', 'UNARCHIVE', 'READ_ARCHIVED', 'CHOSE_PRODUCT', 'UPDATE_TALLY', 'UPDATE_KENEK', 'TRANSFER_ITEMS', 'REDUCE_ITEMS', 'CANCEL_ITEMS') NOT NULL;
